### ISSUE TITLE
insert/import vs. write

### ISSUE THREAD

**Issue by karissa** [ropensci/rdat#7]
heyo

there's currently an 'insert' command which is using 'import' under the hood, but in some cases people might want to use 'write', which is for non-tabular data.

We are aiming for a release on Monday. Do you think you would like to add 'write' before then, or at the very least, rename 'insert' to 'import' so its less confusing when 'write' is added?

**Comment by jeroenooms** [comment]
What exactly does write do? Does it use ndjson as well?

I chose the term `insert` because it abstracts the underlying data interchange method: it inserts a dataset into the store, just like an insert command does for a database. Currently this is implemented using ndjson `import` tool, but it is entirely possible that future versions use different mechanics for insert, e.g. direct bindings to an actual C or JS api.

**Comment by karissa** [comment]
Write is for blob data. No ndjson https://github.com/maxogden/dat/blob/beta/beta-cli-api.md#dat-write
